[package]
name = "treeupdt"
version = "0.1.0"
edition = "2021"
authors = [""]
description = "Keep your dependency tree fresh"
license = "MIT"

[[bin]]
name = "treeupdt"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
glob = "0.3"
regex = "1.11.1"
colored = "2.1"
walkdir = "2.4"
tree-sitter = "0.22"
tree-sitter-nix = "0.3"
semver = "1.0"
reqwest = { version = "0.11", features = ["json"] }
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
tokio = { version = "1", features = ["full"] }
toml_edit = "0.22"
dirs = "5.0"
sha2 = "0.10"
serde_yaml = "0.9"

[dev-dependencies]
tempfile = "3.8"
pretty_assertions = "1.4"
